#!/usr/bin/env bash
# Neutral YAML-frontmatter parsing + projection helpers.
# Canon files begin with a `---` frontmatter block followed by a markdown body.
# Profiles decide which neutral fields to emit per IDE (an allowlist), so strict
# schemas (e.g. OpenCode additionalProperties:false) can never be violated.

SPECFORGE_MARKER="SPECFORGE-GENERATED"

sf_marker_html() {
  echo "<!-- ${SPECFORGE_MARKER} — do not edit; regenerated by \`sf update\` -->"
}
sf_marker_hash() {
  echo "# ${SPECFORGE_MARKER} — do not edit; regenerated by \`sf update\`"
}

# Read one scalar frontmatter field. Echoes the trimmed value (empty if absent).
sf_fm_field() {
  local file="$1" key="$2"
  awk -v key="$key" '
    NR==1 && $0=="---" { infm=1; next }
    infm && $0=="---" { exit }
    infm {
      line=$0
      # match "key:" at start
      if (line ~ ("^" key ":")) {
        sub("^" key ":[[:space:]]*", "", line)
        print line
        exit
      }
    }
  ' "$file" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"
}

# Echo the markdown body (everything after the closing frontmatter ---).
sf_fm_body() {
  local file="$1"
  awk '
    NR==1 && $0=="---" { infm=1; next }
    infm && $0=="---" { infm=0; started=1; next }
    started { print }
    !infm && !started { print }   # files without frontmatter: print all
  ' "$file"
}

# snake_case a slug/id for tools (codex) that want underscores.
sf_snake() {
  echo "$1" | tr '-' '_'
}

# Write $1 (a temp file) to $2 only if $2 is ours (has the marker) or absent.
# Files lacking the marker are user-authored and preserved.
sf_write_if_ours() {
  local tmp="$1" dest="$2" label="${3:-$2}" dry="${4:-false}"
  if [ -e "$dest" ] && ! grep -qF "$SPECFORGE_MARKER" "$dest" 2>/dev/null; then
    echo "  ⚠ preserving user-authored $label (no marker)"
    return 0
  fi
  if [ -f "$dest" ] && cmp -s "$tmp" "$dest"; then
    return 0
  fi
  if [ "$dry" = true ]; then
    echo "  → would write $label"
    return 0
  fi
  mkdir -p "$(dirname "$dest")"
  cp "$tmp" "$dest"
  echo "  ✓ wrote $label"
}

# Remove generated (marker-bearing) entries under a directory so orphans retire.
# For plain files: remove if file contains the marker.
# For skill dirs: remove dir if its SKILL.md contains the marker.
sf_sweep_generated_files() {
  local dir="$1"
  [ -d "$dir" ] || return 0
  local f
  for f in "$dir"/*; do
    [ -f "$f" ] || continue
    if grep -qF "$SPECFORGE_MARKER" "$f" 2>/dev/null; then rm -f "$f"; fi
  done
}

sf_sweep_generated_skilldirs() {
  local dir="$1"
  [ -d "$dir" ] || return 0
  local d
  for d in "$dir"/*/; do
    [ -d "$d" ] || continue
    if [ -f "$d/SKILL.md" ] && grep -qF "$SPECFORGE_MARKER" "$d/SKILL.md" 2>/dev/null; then
      rm -rf "$d"
    fi
  done
}
